version: '3'

services:
  turkiyeokureact:
    image: reactappturkiyeoku:v1
    deploy:
      restart_policy:
        condition: "any"
        delay: "0"
        max_attempts: 3
        window: "30s"
    ports:
      - 3000:3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.turkiyeokureact.rule=Host(`react.turkiyeoku.com`)"
      - "traefik.http.routers.turkiyeokureact.entrypoints=https"
      - "traefik.http.routers.turkiyeokureact.tls.certresolver=http"

networks:
  proxy:
    external: true
